title: Lemonflow.docs
description: Comprehensive documentation for Lemonflow.ai services
theme: minima
url: "https://lemonflow-ai.github.io"
baseurl: "/lemonflow-docs"

# Site settings
author: Lemonflow.ai
email: tech@lemonflow.ai
website: https://lemonflow.ai

# Navigation structure
# Removed header_pages to keep header clean
# header_pages:

# SEO
lang: en
tagline: AI-powered customer service solutions

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social
github_username: lemonflow-ai
